### ISSUE TITLE
[question] Switching ports "up" and "down"

### ISSUE THREAD

**Issue by ryneeverett** [wavestone-cdt/dyode#17]
In your slides you say about "cutting the cable":

> In theory, advanced attacks may allow to send information the other way around, for example by switching ports “up” and “down”

Could you elaborate on this? Are you referring to [Auto MDI-X](https://en.wikipedia.org/wiki/Medium-dependent_interface#Auto_MDI-X)? Are you aware of any research on this?

Thanks,

**Comment by arnaudsoullie** [comment]
It was a long time ago and I do not remember...
Yes, auto MDI-X might perhaps be abused for that.

I would need to dive into Ethernet linkup process rabbit hole to answer correctly; my take today is that with proper configuration of the Ethernet interfaces it might not be so easily possible.
