### ISSUE TITLE
What is the point of capacitors ?

### ISSUE THREAD

**Issue by IArchi** [wavestone-cdt/dyode#18]
Hello,

Could you let me know why you need 0.1uF capacitors around the optocoupler ?
Is it to smooth the input voltage ?

Thanks for your time

**Comment by arnaudsoullie** [comment]
I do not really know,  I just followed the datasheet instructions :)
![image](https://github.com/wavestone-cdt/dyode/assets/93718/8cc8161d-74f5-4dfa-8090-f7c44fc3685c)

**Comment by netcarver** [comment]
@IArchi Take a look at the [bypass/decoupling capacitor article on wikipedia](https://en.wikipedia.org/wiki/Decoupling_capacitor) for more info. Here's a small section, but it's not limited to this - though it is the way I tend to think about them.

![image](https://github.com/wavestone-cdt/dyode/assets/16049/492633d2-53d0-4972-aeab-076d06ffbcde)
