### ISSUE TITLE
Can't establish connection with v1

### ISSUE THREAD

**Issue by nickcounts** [wavestone-cdt/dyode#2]
Any assistance you can provide with media converter configuration? We can't seem to get the hardware layer to work.

Can you provide more information regarding what DIP switch settings you used for the media converters and what indicator lights should be illuminated?

**Comment by nickcounts** [comment]
We are trying to follow your guide. Spoofing the carrier signal appears to be the issue. Here are some photos of our setup:

![52339670237__09029d61-0ac6-4bf7-b121-be6e3c41b20a jpg](https://user-images.githubusercontent.com/10506020/28892331-99098cf2-779b-11e7-8959-1bd543fe7bbd.jpeg)

![52339682465__7150b491-9b45-4f6b-9d3b-9e6f1b689425 jpg](https://user-images.githubusercontent.com/10506020/28892385-d14c9b7c-779b-11e7-8fc1-b23d778afe6a.jpeg)

**Comment by nickcounts** [comment]
I believe we had a combination of hardware and software layer issues.

We will post our working switch configuration. Once we started seeing ARP queries (used wireshark on the receiver) we knew we had the hardware working.

**Comment by arnaudsoullie** [comment]
Hi Nick, 
From your last update I get that data is flowing from IN to OUT ?
Let me know if you encounter any software issue.
In the picture you posted, it seems that the 3rd converter is connected by its RX to the TX of the OUT converter. Shouldn't it be connected to the RX of the IN converter ?

**Comment by EBUJOLD** [comment]
Our problem was two parts:
1. Our machines forgot their ARP addresses upon reboot
2. We didn't have our DIP switches configured correctly.

I have documented how we got our data diode to work (using DYODE software) on my repo:

[https://github.com/EBUJOLD/data-diode](https://github.com/EBUJOLD/data-diode) 

Thank you for your time.
