### ISSUE TITLE
DYODE V1 dyode_out.py

### ISSUE THREAD

**Issue by pooryasheikh** [wavestone-cdt/dyode#3]
hi, at first thank for this app.
i have problem to run dyode_out.py:
[root@CentOSOUT DYODE v1 (full)]# sudo python dyode_out.py
INFO:root:Loading config file
INFO:root:Configuration name : Dyode test
INFO:root:Configuration version : 1.0
INFO:root:Configuration date : 2016-05-04
INFO:root:Dyode input ip : 192.168.1.100 (08:00:27:9e:5d:fb)
INFO:root:Dyode output ip : 192.168.1.150 (08:00:27:9e:5d:fb)
DEBUG:root:Parsing "Partage de fichier 1"
DEBUG:root:Trying to launch a new process for module "Partage de fichier 1"
DEBUG:root:Instanciating a file transfer module :: Partage de fichier 1
DEBUG:root:Waiting for file ...
DEBUG:root:2017-12-03 16:30:17.712871
DEBUG:root:{'in': '/home/pi/in', 'type': 'folder', 'port': 9600, 'out': '/home/pi/out'}
DEBUG:root:9600
DEBUG:root:udp-receiver --nosync --mcast-rdv-addr 10.0.1.1 --interface eth1 --portbase 9600 -f 'manifest_Partage de fichier 1.cfg'
Process Partage de fichier 1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "dyode_out.py", line 28, in launch_agents
    dyode.file_reception_loop(properties)
  File "/root/dyode/DYODE v1 (full)/dyode.py", line 44, in file_reception_loop
    wait_for_file(params)
  File "/root/dyode/DYODE v1 (full)/dyode.py", line 69, in wait_for_file
    files = parse_manifest(manifest_filename)
  File "/root/dyode/DYODE v1 (full)/dyode.py", line 36, in parse_manifest
    for item, value in parser.items('Files'):
  File "/usr/lib64/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)

how can i solve it?

**Comment by arnaudsoullie** [comment]
Hello !

Is it possible to post logs from the input diode from the same time ?

Can you poste the content of ``manifest_Partage de fichier 1.cfg`` ?

Does this happen for the first file or after a certain period of time ?

**Comment by pooryasheikh** [comment]
hello, thanks for reply.
i just compile the input dyode without any problem after that i go to output dyode and try to compile, but get errors
I don’t have "manifest_Partage de fichier 1.cfg” file in my Dyode folder.

Dyode OUT:
[root@CentOSOUT DYODE v1 (full)]# python dyode_out.py 
INFO:root:Loading config file
INFO:root:Configuration name : Dyode test
INFO:root:Configuration version : 1.0
INFO:root:Configuration date : 2016-05-04
INFO:root:Dyode input ip : 192.168.1.100 (08:00:27:9e:5d:fb)
INFO:root:Dyode output ip : 192.168.1.150 (08:00:27:9e:5d:fb)
DEBUG:root:Parsing "Partage de fichier 1"
DEBUG:root:Trying to launch a new process for module "Partage de fichier 1"
DEBUG:root:Instanciating a file transfer module :: Partage de fichier 1
DEBUG:root:Waiting for file ...
DEBUG:root:2017-12-03 17:48:17.820088
DEBUG:root:{'in': '/home/pi/in', 'type': 'folder', 'port': 9600, 'out': '/home/pi/out'}
DEBUG:root:9600
DEBUG:root:udp-receiver --nosync --mcast-rdv-addr 10.0.1.1 --interface eth1 --portbase 9600 -f 'manifest_Partage de fichier 1.cfg'
Process Partage de fichier 1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "dyode_out.py", line 28, in launch_agents
    dyode.file_reception_loop(properties)
  File "/root/dyode/DYODE v1 (full)/dyode.py", line 44, in file_reception_loop
    wait_for_file(params)
  File "/root/dyode/DYODE v1 (full)/dyode.py", line 69, in wait_for_file
    files = parse_manifest(manifest_filename)
  File "/root/dyode/DYODE v1 (full)/dyode.py", line 36, in parse_manifest
    for item, value in parser.items('Files'):
  File "/usr/lib64/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
NoSectionError: No section: ‘Files'


DYODE IN:
[root@CentOSIN DYODE v1 (full)]# sudo python ./dyode_in.py 
INFO:root:Loading config file
INFO:root:Configuration name : Dyode test
INFO:root:Configuration version : 1.0
INFO:root:Configuration date : 2016-05-04
INFO:root:Dyode input ip : 192.168.1.100 (08:00:27:9e:5d:fb)
INFO:root:Dyode output ip : 192.168.1.150 (08:00:27:9e:5d:fb)
DEBUG:root:Number of modules : 1
DEBUG:root:Max bitrate per module : 8.0 mbps
DEBUG:root:Parsing Partage de fichier 1
DEBUG:root:Trying to launch a new process for module Partage de fichier 1
DEBUG:root:Partage de fichier 1
DEBUG:root:{'bitrate': 8.0, 'in': '/home/pi/in', 'type': 'folder', 'port': 9600, 'out': '/home/pi/out'}
DEBUG:root:Instanciating a file transfer module :: Partage de fichier 1
DEBUG:root:Function "folder" launched with params {'bitrate': 8.0, 'in': '/home/pi/in', 'type': 'folder', 'port': 9600, 'out': '/home/pi/out'}: 
DEBUG:root:watching :: /home/pi/in

**Comment by pooryasheikh** [comment]
problem solved. i didnt change those lines.
Thanks for everythings.
In dyode.py on both machines, make the following changes:

On line 55: We changed the IP address to our highside address
On line 55: We changed eth1 to our highside ethernet adapter ID (eth3)
On line 107: We changed the IP addresses to our lowside IP address
On line 109: We changed eth1 to our lowside ethernet adapter ID (eth0)
