### ISSUE TITLE
conection error 111

### ISSUE THREAD

**Issue by raspifuzzy** [wavestone-cdt/dyode#4]
Thanks for share your project.
I  built the v2 version using RaspPi3 and followed your steps but receive following error on Input Raspberry.
IP is the Input Raspberry

INFO:root:Loading config file
INFO:root:Configuration name : Dyode v2
INFO:root:Configuration version : 1.0
INFO:root:Configuration date : 2017-07-25
DEBUG:root:Parsing Automate Modbus 1
DEBUG:root:Trying to launch a new process for module Automate Modbus 1
DEBUG:root:Automate Modbus 1
DEBUG:root:{'coils': ['0-1'], 'registers': ['0-105'], 'port_out': 502, 'ip': '192.168.78.50', 'type': 'modbus', 'port': 9400}
DEBUG:root:Modbus agent : Automate Modbus 1
DEBUG:root:Modbus Loop
Performing an action which may throw an exception.
ERROR:pymodbus.client.sync:Connection to (192.168.78.50, 502) failed: [Errno 111] Connection refused
DEBUG:root:['0-105']
DEBUG:root:['0-1']
DEBUG:root:Register start number : 0
DEBUG:root:Register end number : 105
DEBUG:root:Number of registers to read : 105
ERROR:pymodbus.client.sync:Connection to (192.168.78.50, 502) failed: [Errno 111] Connection refused
DEBUG:root:Error connecting to 192.168.78.50
DEBUG:root:Modbus Error: [Connection] Failed to connect[192.168.78.50:502]
DEBUG:root:Data size : 25
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
Process Automate Modbus 1:
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "dyode_in.py", line 24, in launch_agents
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    modbus.modbus_loop(module, properties)
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/pi/dyode_in/modbus.py", line 108, in modbus_loop
KeyboardInterrupt
    modbus_send_serial(data, properties)
  File "/home/pi/dyode_in/modbus.py", line 100, in modbus_send_serial
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    ser.write(encoded_data)
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 542, in write
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
    abort, ready, _ = select.select([self.pipe_abort_write_r], [self.fd], [], None)
KeyboardInterrupt

**Comment by raspifuzzy** [comment]
Remaks:
Maybe I'm wrong but according to the Datasheet, I think there is a mistake in the pinout's of the HCPL-7723-000E DIP-8

5 = GND
8 = + 3.3V
6 = Vout

**Comment by arnaudsoullie** [comment]
From the error log it seems that your Input Rapsberry is not able to connect to the PLC:
``ERROR:pymodbus.client.sync:Connection to (192.168.78.50, 502) failed: [Errno 111] Connection refused``

What kind of device is 192.168.78.50 ? Is a modbus slave running on port 502 ? You can use ``mbtget`` to test your Modbus slave prior to implementing DYODE.

**Comment by arnaudsoullie** [comment]
Regarding the pinout, it is not very clear in the Wiki, but when I mention ``3.3V -> 3`` for the input Raspi, I mean the PIN 3 on the pin header, not on the optocoupler.
This is a bit confusing I have to admit.

**Comment by raspifuzzy** [comment]
Device is a RaspPi3. I only install the latest Raspian Version, and then installed your setup step by step.
I had to admit that I have no experience with python or programming in general.

mbtget gives me following message:

server connect [localhost]:502 failed

**Comment by arnaudsoullie** [comment]
OK.
You should have:
[Modbus device (slave)]<-->[input raspi]-->optocoupler-->[output raspi]<-->[Modbus device (master)]
At the moment it seems that you do not have a Modbus slave working since you're not able to query it using ``mbtget``

What is the modbus device you're trying to get data from ?

**Comment by raspifuzzy** [comment]
Well actually I have both Raspberry's connected on the same router (Fritzbox) via LAN.
[Router] <--> Raspi 192.168.78.50 --> optocoupler --> Raspi 192.168.78.49 <--> [Router]


When typing "sudo python dyode_out.py" on the output raspi it gives me until pressing "^C":



INFO:root:Loading config file
INFO:root:Configuration name : Dyode v2
INFO:root:Configuration version : 1.0
INFO:root:Configuration date : 2017-07-25
DEBUG:root:Parsing "Automate Modbus 1"
DEBUG:root:Trying to launch a new process for module "Automate Modbus 1"
DEBUG:root:Modbus agent : Automate Modbus 1
DEBUG:root:Modbus master module : Automate Modbus 1
INFO:pymodbus.server.async:Starting Modbus TCP Server on 0.0.0.0:502
DEBUG:root:Updating : Automate Modbus 1
DEBUG:root:{'coils': ['0-1'], 'registers': ['9-105'], 'port_out': 502, 'ip': '192.168.78.50', 'type': 'modbus', 'port': 9400}
DEBUG:root:['9-105']
ERROR:root:Error obtaining Modbus values
ERROR:root:'NoneType' object has no attribute '__getitem__'
DEBUG:root:Updating : Automate Modbus 1
DEBUG:root:{'coils': ['0-1'], 'registers': ['9-105'], 'port_out': 502, 'ip': '192.168.78.50', 'type': 'modbus', 'port': 9400}
DEBUG:root:['9-105']
ERROR:root:Error obtaining Modbus values
ERROR:root:'NoneType' object has no attribute '__getitem__'
DEBUG:root:Updating : Automate Modbus 1
DEBUG:root:{'coils': ['0-1'], 'registers': ['9-105'], 'port_out': 502, 'ip': '192.168.78.50', 'type': 'modbus', 'port': 9400}
DEBUG:root:['9-105']

**Comment by arnaudsoullie** [comment]
Well I can only suggest to take a look at the  [presentations of this project](https://github.com/wavestone-cdt/dyode/tree/master/Talks) in order for you to understand the use cases.

1. Two Raspberry Pis are needed for DYODE, but you also need Modbus devices that will use DYODE as a data diode. DYODE itself is useless if you have no data to transmit, which seems to be your case. You need to modify the config file to define what is the modbus device from which to get data. 
If you do not have any additional Modbus device, then install a modbus simulator on the INPUT Raspi and set 127.0.0.1 as the ip of the plc.
You get ``ERROR:root:Error obtaining Modbus values`` on the output because you have ``ERROR:pymodbus.client.sync:Connection to (192.168.78.50, 502) failed: [Errno 111] Connection refused`` on the input
2. While it is acceptable for testing, please note that it does not make any sense to connect both Raspberry Pis to the same router, as it will allow the data diode to be trivially bypassed.

**Comment by raspifuzzy** [comment]
Thanks a lot. I see more clear now, and will try your suggestion in new year cause hollydays now. 
Bonne fin d‘année et joyeuses fêtes!

**Comment by arnaudsoullie** [comment]
I just realized I never closed this issue, doing it now
