### ISSUE TITLE
3d file for the editing

### ISSUE THREAD

**Issue by lcheng62** [wavestone-cdt/dyode#6]
Hi,

Do you still have the scad file(or equivalent file) that I can make the edit on the v2 case hardware? 

Thanks,

**Comment by arnaudsoullie** [comment]
Waouh. Sorry for the very delayed answer..
Here's the link to the case on TinkerCAD: https://www.tinkercad.com/things/6vvMWsDaUBd

In addition, I attached the .STL and .OBJ files
[DYODE-Pi0-case bottomv1.zip](https://github.com/wavestone-cdt/dyode/files/6327041/DYODE-Pi0-case.bottomv1.zip)
[DYODE-Pi0-case bottomv1.zip](https://github.com/wavestone-cdt/dyode/files/6327042/DYODE-Pi0-case.bottomv1.zip)
