### ISSUE TITLE
DIP switch Status

### ISSUE THREAD

**Issue by biswaKL** [wavestone-cdt/dyode#7]
Can you please share your status which you set the for the DIP switches. 
I guess its not working for normal ones (without DIP)

**Comment by adamliq** [comment]
Biswakl did you get any further with this. As its not working for my tp-link media convertor with no dip switch.

**Comment by biswaKL** [comment]
nope.. it was a dead end.

**Comment by ajs-88** [comment]
@biswaKL have you tested any media converter with DIP switch? can you share model information?

**Comment by biswaKL** [comment]
@ajs-88 it was a dead end for me.
