### ISSUE TITLE
Media Converters

### ISSUE THREAD

**Issue by therion667** [wavestone-cdt/dyode#8]
Guys,
I have been trying to set your DYODE up. software setup seems fine and running but my converters Ultimode M-023M doesn not want to establish a correct link.
When I connect Tx to Rx and Tx to Rx the files are received but when I disconnect Tx cable from receiver converter and connect it to another converter to Tx socket the flow stops. Maybe the dead end converter needs to have some specific function?
Are there any specific parameters of TpLinks that you've used? I can try to buy and use the ones that you've used if neccecery.

Thanks in advance!

**Comment by arnaudsoullie** [comment]
Hi!

This behavior might indeed be linked to the specifics of the Copper/Optical converters. I can only confirm that I did not do anything special to the ones I used. I used TP-LINK MC100CM.

**Comment by therion667** [comment]
I came up with idea that maybe the addresses are wrong like in [here](https://github.com/wavestone-cdt/dyode/issues/3). Basing on [this](https://www.udpcast.linux.lu/satellite.html) line 100 in dyode.py has two same addresses which should be different? I will take a look at this next week and mingle with udpcast. If this won't work I will buy those converters. Please dont close I will try to post something afterwards.

**Comment by therion667** [comment]
Ok so seems like on wireshark I'm getting only ARP done by eth0 on OUT part. Anything special about IP configuration on the diodes? I just set IP 10.0.1.1/24 and that's it.

**Comment by arnaudsoullie** [comment]
You need to make sure that you set up MAC addresses correctly in the configuration file : 
`dyode_in:
  ip: 10.0.1.1
  mac: b8:27:eb:89:1e:f3
dyode_out:
  ip: 10.0.1.2
  mac: b8:27:eb:b1:ff:ab`

MAC addresses need of course to be the ones of your Ethernet/Optical converters

Since there is no bidirectionnal comms, ARP requests do not go through.

Have you defined the right info in the config file on each side?

**Comment by therion667** [comment]
Sure, the config is done correctly.
I've decided to set static MACs with IPs in /etc/ethers on both sides and well the data started to flow. No more ARP packets on wireshark.
I've also managed to send something using netcat. But udpcast seems to fail. When I use clear command copied from your code I get strange outcomes:
1. Waiting for file is long. IN Pi is actually sending 6 bit file every 3 seconds. For OUT to see the file takes really long time.
2. When using the command I can see transfer but no file. Under -f flag I just paste the /home/pi/in dir.
When I use your code I get this:
1. Nothing is showing up and the udp-receive command has 'Manifest folder 1.cfg' after -f flag. Is that correct?
2. Even after long time sometimes the manifest file comes through and file with HSD48FDSA is being created empty. Sometimes the manifest file contains the contents of the file that I've sent or [FILE] and directory plus hash but nothing else happens after that.

Sorry for expanding the issue for so long. Maybe some settings changed with newer Raspbian releases.

**Comment by aruljane** [comment]
> You need to make sure that you set up MAC addresses correctly in the configuration file :
> `dyode_in: ip: 10.0.1.1 mac: b8:27:eb:89:1e:f3 dyode_out: ip: 10.0.1.2 mac: b8:27:eb:b1:ff:ab`
> 
> MAC addresses need of course to be the ones of your Ethernet/Optical converters
> 
> Since there is no bidirectionnal comms, ARP requests do not go through.
> 
> Have you defined the right info in the config file on each side?

Hi @arnaudsoullie kindly elaborate on this point "MAC addresses need of course to be the ones of your Ethernet/Optical converters". Currently I have configured dyode_in 10.1.1.1 & raspberry pi eth0 Mac address and dyode_out 10.1.1.2 & raspberry pi eth0 Mac address and its not working. I verified ARP table on both ends and they are correct. But its not working. IM using MC200CM TPLINK. From your point how can I extract MAC address of Ethernet / Optical converters? Its a Layer 1 device right? Kindly advise.

**Comment by ajs-88** [comment]
@arnaudsoullie Is there any limitations to keep in mind when choosing a copper to fiber media converter?

**Comment by therion667** [comment]
I've fixed the issues.
Seemed like the highside mediaconverter needed to be with DIP switch and not the rest. I might test on other models in the future.
Right now I am working on the speed. For now I can get as high as 100 mb a 1 minute which for my use is not that bad. I might be fooling around with UDP cast settings. With more speed the stability drops and lowside dyode gets error on hashing the incoming file (it finished downloading even that the file is still flowing). Less speed = more stability.

**Comment by ajs-88** [comment]
@therion667 great work! Kindly suggest me which media converter you tested? Model and specifications

**Comment by ajs-88** [comment]
@therion667 Kindly advise which model worked for you?

**Comment by ajs-88** [comment]
@therion667 I kindly request you to share the model details you have successfully tested.

**Comment by therion667** [comment]
@ajs-88 sure,
so it was tested on mentioned:
Ultimode M-023M
TP-LINK MC100CM without DIP switch
Allied Telesis MC102XL

it worked only on TP-LINK MC100CM with DIp switch with Auto Negotiation OFF

**Comment by Vrolijk** [comment]
Hi,

Have you seen the 2 optic-copper solution from klockcykel? 
https://github.com/klockcykel/godiode

For their project they used 2 TP-Link MC200CM gigabit optic-copper converters with a small hardware mod. Could be a nice extra option for your great project.

Regards,
René

**Comment by arnaudsoullie** [comment]
That's interesting thank you!
